#!/usr/bin/env bash

SCRIPT=$(readlink -f "${HOME}/.i3")
BASEDIR=$(dirname $SCRIPT)
DOTFILESDIR=$(realpath "${BASEDIR}")

sh $HOME/.i3/scripts/merge_configs.sh

if [[ -f "${DOTFILESDIR}/x/resources" ]] ; then
    xrdb -merge "${DOTFILESDIR}/x/resources"
fi

