#!/usr/bin/env bash

echo $_ > /dev/null
SCRIPT=$(readlink -f $_)
BASEDIR=$(dirname $SCRIPT)
DOTFILESDIR=$(realpath "${BASEDIR}/..")


if [[ -f "${BASEDIR}/Xresources" ]] ; then
    xrdb -merge "${BASEDIR}/resources"
fi

