#!/usr/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)
DOTFILESDIR=$(realpath "${BASEDIR}/..")


sudo -v

if [ $(command -v python) ]; then
    sudo python -m ensurepip --upgrade
    sudo python -m pip install -r "${DOTFILESDIR}/requirements.txt"
else
    echo "You are running a system without python installed you dummy!"
fi;


update_repo() {
    repourl=$(git -C $2 config --get remote.origin.url 2>/dev/null)
    ret=$?
    if [ $ret -ne 0 ] || [ $repourl != $1 ]; then
        # Not a repo / Wrong URL
        sudo rm -rf $2
        sudo git clone $1 $2
    else
        # Update instead
        sudo git -C $2 reset --hard
        sudo git -C $2 pull
    fi
}

sudo apt-get install -y git vim zsh i3 python3 python3-pip rxvt-unicode tmux curl compton feh ranger
# sudo pacman -Sy git vim zsh i3 python3 python3-pip rxvt-unicode tmux curl compton feh ranger

# git clone https://github.com/mavnn/mintty-colors-solarized.git "${DOTFILESDIR}/themes/solarized/mintty"
update_repo https://github.com/solarized/xresources.git "${DOTFILESDIR}/themes/solarized/xresources"
update_repo https://github.com/seebi/dircolors-solarized.git "${DOTFILESDIR}/themes/solarized/dircolors"

