#!/usr/bin/env sh

echo $_ > /dev/null
SCRIPT=$(readlink -f $_)
BASEDIR=$(dirname $SCRIPT)
DOTFILESDIR=$(realpath "${BASEDIR}/..")

sudo -v

. "${DOTFILESDIR}/scripts/bootstrap"

smartlink () {
    LINK_DEST=$1
    LINK_SRC=$2
    if [ -h $LINK_DEST ] || [ -L $LINK_DEST ] || [ -e $LINK_DEST ]; then
        sudo rm -rf $LINK_DEST;
    fi;
    ln -s $LINK_SRC $LINK_DEST
}

smartlink "${HOME}/.zshrc"       "${DOTFILESDIR}/zsh/rc.zsh"
smartlink "${HOME}/.zshenv"      "${DOTFILESDIR}/zsh/env.zsh"
smartlink "${HOME}/.tmux.conf"   "${DOTFILESDIR}/tmux.conf"
smartlink "${HOME}/.vimrc"       "${DOTFILESDIR}/vimrc.vim"
smartlink "${HOME}/.i3"          "${DOTFILESDIR}/i3"
smartlink "${HOME}/.xprofile"    "${DOTFILESDIR}/x/profile"
smartlink "${HOME}/.xsession"    "${DOTFILESDIR}/x/session"
smartlink "${HOME}/.xinitrc"     "${DOTFILESDIR}/x/initrc"

sudo -u $USER chsh -s $(which zsh)
