#!/usr/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)
BASEDIR=$(realpath "${BASEDIR}/..")

smartlink () {
    LINK_DEST=$1
    LINK_SRC=$2
    if [ -e "${LINK_DEST}" ]; then
        rm -rf "${LINK_DEST}"
    fi
    ln -s "${LINK_SRC}" "${LINK_DEST}"
}

smartlink "${HOME}/.zshrc"       "${BASEDIR}/zshrc"
smartlink "${HOME}/.tmux.conf"   "${BASEDIR}/tmux.conf"
smartlink "${HOME}/.vimrc"       "${BASEDIR}/vimrc"
smartlink "${HOME}/.i3"          "${BASEDIR}/i3"
smartlink "${HOME}/.xinitrc"     "${BASEDIR}/xinitrc"

sudo -u $USER chsh -s $(which zsh)
