#!/usr/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)
DOTFILESDIR=$(realpath "${BASEDIR}/..")

pushd $DOTFILESDIR
sudo sh "scripts/bootstrap"

sudo git reset --hard
sudo git pull

sudo sh "scripts/bootstrap"
sudo apt-get update
sudo sh "scripts/setup"
popd
